name: deploy

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Version
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 16
      - uses: borales/actions-yarn@v3.0.0
        name: Install dependencies
        with:
          cmd: install
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{secrets.GPG_KEY}}
          passphrase: ${{secrets.GPG_PASS}}
          git_committer_name: ${{secrets.GIT_NAME}}
          git_committer_email: ${{secrets.GIT_EMAIL}}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Publish
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
        run: |
          git config --local gpg.program $(which gpg)
          npm run pkg:version
          git push --follow-tags origin ${{github.ref_name}}

  production:
    name: Deploy to production
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    environment:
      name: production
      url: https://moonlit.works/
    outputs:
      semver: ${{ steps.package.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1
      - name: Set image
        id: tag
        run: |
          echo "::set-output name=bare::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}"
          echo "::set-output name=version::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{steps.package.outputs.version}}"
      - uses: docker/login-action@v1
        name: Login to docker registry
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t ${{ steps.tag.outputs.version }} .
      - name: Push image
        run: docker image push ${{ steps.tag.outputs.bare }} --all-tags
      - name: Update deployment image
        uses: eyzi/k8s-deploy@v1
        with:
          api_url:    ${{ secrets.DEPLOY_URL }}
          api_token:  ${{ secrets.DEPLOY_TOKEN }}
          image:      ${{ steps.tag.outputs.bare }}
          version:    ${{ steps.version.outputs.semver }}
